- src: andrewrothstein.packer
  path: roles/

- src: andrewrothstein.unarchive-deps
  path: roles/

# - src: http://github.com/cliffano/ansible-role-droplet-docker
#   path: roles/

- src: cliffano.droplet-docker
  path: roles/

# - src: http://github.com/cliffano/ansible-role-newrelic-unix
#   path: roles/

- src: cliffano.newrelic-unix
  path: roles/

- src: Comcast.sdkman
  path: roles/

- src: geerlingguy.homebrew
  path: roles/

#- src: rack-roles.newrelic
#  path: roles/

- src: leonidas.nvm
  path: roles/

- src: rvm_io.rvm1-ruby
  path: roles/

- src: valentinogagliardi.sysdig
  path: roles/
