collections:
  - name: community.docker

roles:
  - src: andrewrothstein.packer
    path: roles/

  - src: andrewrothstein.terraform
    path: roles/

  - src: andrewrothstein.unarchive-deps
    path: roles/

  # - src: http://github.com/cliffano/ansible-role-droplet-docker
  #   path: roles/

  - src: cliffano.droplet-docker
    path: roles/

  # - src: http://github.com/cliffano/ansible-role-newrelic-unix
  #   path: roles/

  - src: cliffano.newrelic-unix
    path: roles/

  - src: Comcast.sdkman
    path: roles/

  - src: gantsign.oh-my-zsh
    path: roles/

  - src: geerlingguy.homebrew
    path: roles/

  - src: grzegorznowak.nvm_node
    path: roles/

  #- src: rack-roles.newrelic
  #  path: roles/

  - src: rkhmelichek.mas
    path: roles/

  - src: rvm.ruby
    path: roles/

  - src: jebovic.sysdig
    path: roles/

