collections:
  - name: community.general
  - name: community.docker
  - name: geerlingguy.mac

roles:
  - src: andrewrothstein.packer
    path: roles/

  - src: andrewrothstein.terraform
    path: roles/

  - src: andrewrothstein.unarchive-deps
    path: roles/

  - src: cliffano.droplet-docker
    path: roles/

  - src: cliffano.minecraft_java
    path: roles/

  - src: cliffano.fabricmc
    path: roles/

  - src: cliffano.newrelic-unix
    path: roles/

  - src: https://github.com/cliffano/ansible-role-studio-dev
    path: roles/

  - src: Comcast.sdkman
    path: roles/

  - src: gantsign.oh-my-zsh
    path: roles/

  - src: grzegorznowak.nvm_node
    path: roles/

  - src: rvm.ruby
    path: roles/

  - src: jebovic.sysdig
    path: roles/

