- src: andrewrothstein.packer
  path: roles/

- src: andrewrothstein.unarchive-deps
  path: roles/

# - src: http://github.com/cliffano/ansible-role-droplet-docker
#   path: roles/

- src: cliffano.droplet-docker
  path: roles/

# - src: http://github.com/cliffano/ansible-role-newrelic-unix
#   path: roles/

- src: cliffano.newrelic-unix
  path: roles/

- src: Comcast.sdkman
  path: roles/

- src: geerlingguy.homebrew
  path: roles/

#- src: rack-roles.newrelic
#  path: roles/

- src: gvillalta99.nvm
  path: roles/

- src: rkhmelichek.mas
  path: roles/

- src: altermn.rvm
  path: roles/

- src: jebovic.sysdig
  path: roles/
