# - src: cliffano.droplet-docker
#   path: roles/

# - src: http://github.com/cliffano/ansible-role-droplet-docker
#   path: roles/

- src: cliffano.droplet-docker
  path: roles/

- src: geerlingguy.homebrew
  path: roles/

- src: Rackspace_Automation.newrelic
  path: roles/

- src: leonidas.nvm
  path: roles/

- src: valentinogagliardi.sysdig
  path: roles/
