---
- hosts: ci

  roles:
    - role: leonidas.nvm
      nvm:
        user: jenkins
        version: v0.28.0
        node_version: '4'
      sudo: yes

  tasks:

  - name: Ensure os packages are installed
    apt: name={{ item }} state=present
    with_items:
      - jenkins

  - name: Set Sendman configuration for GD hosts
    template: src={{ workspace }}/dotfiles/studio/sendman/{{ item }}.json dest={{ home }}/.ssh/{{ item }}.json
    with_items:
      - deidara
      - kakuzu
      - kisame
