---
- hosts: cloud-a

  tasks:

  - name: Ensure Terraform states bucket exists
    s3_bucket:
      name: ryokan-tf-states
      region: ap-southeast-2
      versioning: yes
      tags:
        project: ryokan
