---
- hosts: cloud00

  tasks:

  - name: Ensure Terraform states bucket exists
    s3_bucket:
      name: ryokan-tf-states
      region: ap-southeast-2
      versioning: yes
      tags:
        project: ryokan

  # - name: Create IAM policy for API Gateway settings
  #   iam_policy:
  #     iam_type: role
  #     iam_name: studio-apigateway
  #     policy_name: studio-apigateway-policy
  #     policy_document: resources/cloud-a/studio-apigateway-policy.json
  #     state: present

  - name: Apply Terraform project
    community.general.terraform:
      project_path: '../../config/tools/terraform/kumo/'
      state: "present"
      force_init: true
      backend_config:
        region: "ap-southeast-2"
        bucket: "ryokan-tf-states"
        key: "ryokan/kumo.tfstate"