---
- hosts: cloud00

  tasks:

  - name: Ensure Terraform states bucket exists
    s3_bucket:
      name: ryokan-tf-states
      region: ap-southeast-2
      versioning: yes
      tags:
        project: ryokan

  - name: Apply Terraform project
    community.general.terraform:
      project_path: '../../config/tools/terraform/kumo/'
      state: "present"
      force_init: true
      backend_config:
        region: "ap-southeast-2"
        bucket: "ryokan-tf-states"
        key: "ryokan/kumo.tfstate"