---
- hosts: delllatitude00

  vars:
    docker_images:
      - { id: aembuildenv, image: 'shinesolutions/aem-platform-buildenv' }
    main_workspaces:
      - control
    project_workspaces:
      - bussdig
      - busspla
      - bussint

  tasks:

  - name: Ensure utility packages are installed
    ansible.builtin.package:
      name:
        - curl
        - docker
        - telnet
        - wget
      state: latest

  - name: Ensure global node.js packages are installed
    npm: name="{{item}}" global=yes state=present
    with_items:
      - repoman
      - nestor

  - name: Ensure main workspace directories exist
    file: path={{ home }}/dev/workspace-{{ item }} state=directory mode=0755
    with_items: "{{ main_workspaces }}"

  - name: Set Repoman configuration for main workspace repositories
    ansible.builtin.copy: src={{ home }}/dev/workspace-control/config/workspaces/{{ item }}/.repoman.json dest={{ home }}/dev/workspace-{{ item }}/.repoman.json mode='0644'
    with_items: "{{ main_workspaces }}"

  - name: Ensure project workspace directories exist
    file: path={{ home }}/dev/workspace-{{ item }} state=directory mode=0755
    with_items: "{{ project_workspaces }}"

  - name: Set Repoman configuration for project workspace repositories
    ansible.builtin.copy: src={{ home }}/dev/workspace-control/config/workspaces/{{ item }}/.repoman.json dest={{ home }}/dev/workspace-{{ item }}/.repoman.json mode='0644'
    with_items: "{{ project_workspaces }}"
