---
- hosts: delllatitude00

  vars:
    docker_images:
      - { id: aembuildenv, image: 'shinesolutions/aem-platform-buildenv' }
    main_workspaces:
      - control
    project_workspaces:
      - bussaoc
      - bussdig
      - busspla
      - bussint
    nvm_node_version: "16.13.2"
    nvm_dir: "{{ home }}/tools/nvm"
    nvm_user_name: cliffano
    nvm_install_globally: ['nestor', 'repoman'] 
  roles:
    - { role: grzegorznowak.nvm_node, become: yes }
    - { role: andrewrothstein.packer }
    - { role: andrewrothstein.terraform }
    - { role: rvm.ruby, rvm1_rubies: ['ruby-2.7.5', 'ruby-3.1.0'], rvm1_user: 'cliffano', rvm1_gpg_key_server: 'hkp://keyserver.ubuntu.com' }

  tasks:

  - name: Ensure nvm directory exists
    file: path={{ home }}/tools/nvm state=directory

  - name: Set git config
    file: src={{ home }}/dev/workspace-control/config/tools/git/.gitconfig-{{ inventory_hostname }} dest='{{ home }}/.gitconfig' state=link

  - name: Set git config for GitHub repos
    file: src={{ home }}/dev/workspace-control/config/tools/git/.gitconfig-{{ inventory_hostname }}-github dest='{{ home }}/.gitconfig-github' state=link

  - name: Set git config for BitBucket repos
    file: src={{ home }}/dev/workspace-control/config/tools/git/.gitconfig-{{ inventory_hostname }}-bitbucket dest='{{ home }}/.gitconfig-bitbucket' state=link

  - name: Ensure SSH directory exists
    file: path={{ home }}/.ssh/ state=directory

  - name: Ensure SSH config directory exists
    file: path={{ home }}/.ssh/config.d/ state=directory

  - name: Set SSH configuration
    file: src={{ home }}/dev/workspace-control/config/tools/ssh/{{ item }} dest={{ home }}/.ssh/{{ item }} state=link mode=0600
    with_items:
      - config

  - name: Set project workspaces SSH configuration include
    file: src={{ home }}/dev/workspace-control/config/workspaces/{{ item }}/.ssh_config dest={{ home }}/.ssh/config.d/config-{{ item }} state=link
    with_items: "{{ project_workspaces }}"

  - name: Ensure utility OS packages are installed
    become: yes
    ansible.builtin.package:
      name:
        - curl
        - docker
        - git
        - python3-pip
        - telnet
        - vim
        - wget
      state: latest

  - name: Ensure Python packages are installed
    ansible.builtin.pip:
      name:
        - awscli
      state: latest

  - name: Ensure main workspace directories exist
    file: path={{ home }}/dev/workspace-{{ item }} state=directory mode=0755
    with_items: "{{ main_workspaces }}"

  - name: Set Repoman configuration for main workspace repositories
    ansible.builtin.copy: src={{ home }}/dev/workspace-control/config/workspaces/{{ item }}/.repoman.json dest={{ home }}/dev/workspace-{{ item }}/.repoman.json mode='0644'
    with_items: "{{ main_workspaces }}"

  - name: Ensure project workspace directories exist
    file: path={{ home }}/dev/workspace-{{ item }} state=directory mode=0755
    with_items: "{{ project_workspaces }}"

  - name: Set Repoman configuration for project workspace repositories
    ansible.builtin.copy: src={{ home }}/dev/workspace-control/config/workspaces/{{ item }}/.repoman.json dest={{ home }}/dev/workspace-{{ item }}/.repoman.json mode='0644'
    with_items: "{{ project_workspaces }}"
