---
- hosts: home

  vars:
    homebrew_installed_packages:
      - wget
      - brew-cask
      - jenkins
    homebrew_taps:
      - caskroom/cask
    jenkins_version: '1.590'

  roles:
    # - { role: geerlingguy.homebrew }
    - { role: ansible-role-homebrew }

  tasks:

  - name: Ensure root Homebrew Cask packages are installed
    homebrew_cask: name={{ item }} state=installed
    with_items:
      - java
    sudo: yes

  - name: Set .profile
    lineinfile: dest={{ home }}/.profile line="{{ item }}" state=present backup=yes
    with_items:
      - alias start-jenkins='launchctl load /usr/local/Cellar/jenkins/{{ jenkins_version }}/homebrew.mxcl.jenkins.plist'
      - alias stop-jenkins='launchctl unload /usr/local/Cellar/jenkins/{{ jenkins_version }}/homebrew.mxcl.jenkins.plist'

  - name: Ensure Jenkins is exposed on all interfaces
    replace: dest=/usr/local/Cellar/jenkins/{{ jenkins_version }}/homebrew.mxcl.jenkins.plist regexp='127.0.0.1' replace='0.0.0.0'
