---
- hosts: home

  vars:
    homebrew_installed_packages:
      - xz
      - wget
      - brew-cask
      - jenkins
      - sysdig
    homebrew_taps:
      - caskroom/cask
    jenkins_version: '1.590'

  roles:
    # - { role: geerlingguy.homebrew }
    - { role: ansible-role-homebrew }

  tasks:

  - name: Ensure root Homebrew Cask packages are installed
    homebrew_cask: name={{ item }} state=installed
    with_items:
      - java
    sudo: yes

  - name: Set .bashrc
    lineinfile: dest={{ home }}/.bashrc line="PATH=/usr/local/bin:$PATH" state=present backup=yes

  - name: Set .profile
    lineinfile: dest={{ home }}/.profile line="{{ item }}" state=present backup=yes
    with_items:
      - alias start-jenkins='launchctl load /usr/local/Cellar/jenkins/{{ jenkins_version }}/homebrew.mxcl.jenkins.plist'
      - alias stop-jenkins='launchctl unload /usr/local/Cellar/jenkins/{{ jenkins_version }}/homebrew.mxcl.jenkins.plist'
      - alias transfer-data='rsync -zvr /Volumes/TOSHIBAEXT/data /Volumes/Seagate\ Expansion\ Drive'
      - alias backup-data='rsync -zvr /Volumes/Seagate\ Expansion\ Drive/data ~/Desktop'

  - name: Ensure Jenkins is exposed on all interfaces
    replace: dest=/usr/local/Cellar/jenkins/{{ jenkins_version }}/homebrew.mxcl.jenkins.plist regexp='127.0.0.1' replace='0.0.0.0'
