---
- hosts: macbookair01

  roles:
    - role: gantsign.oh-my-zsh
      users:
        - username: cliffano
          oh_my_zsh:
            theme: bullet-train

  tasks:

    - name: Provision Studio dev tools
      ansible.builtin.import_role:
        name: ansible-role-studio-dev
        # name: cliffano.studio_dev
      vars:
        sdev_username: cliffano
        sdev_home_dir: "{{ home }}"
        sdev_colima_networks:
          - konoha
          - onoki
        sdev_docker_images:
          - { id: 'studio', image: 'cliffano/studio', env_file: "{{ home }}/.env-docker-studio", home_dir: 'root', entrypoint: '/bin/bash' }
          - { id: 'kon-tiki', image: 'cliffano/kon-tiki', env_file: "{{ home }}/.env-docker-kon-tiki", home_dir: 'root', entrypoint: '/bin/bash' }
        sdev_gitconfig_link_src: "{{ home }}/dev/workspace-control/config/system-config/git/.gitconfig-{{ inventory_hostname }}"
        sdev_repoman_link_src: "{{ home }}/dev/workspace-control/config/workspace-config/repoman"
        sdev_ssh_configd_link_src: "{{ home }}/dev/workspace-control/config/system-config/ssh/{{ inventory_hostname }}.ssh_config"
        sdev_ssh_configd_file: "{{ inventory_hostname }}.ssh_config"
        sdev_ssh_config_link_src: "{{ home }}/dev/workspace-control/config/user-config/ssh/config"
        sdev_ssh_private_key_link_src: "{{ home }}/dev/workspace-control/config/user-config/ssh/konoha_id_rsa"
        sdev_ssh_public_key_link_src: "{{ home }}/dev/workspace-control/config/user-config/ssh/konoha_id_rsa.pub"
        sdev_sshkey_name: konoha_id_rsa
        sdev_vscode_workspaces:
          - ansible
          - code-generator
          - github-action
          - makefile
          - nodejs
          - oapicf
          - packer
          - python
        sdev_workspaces:
          - control
          - garage
          - g10
          - kon-tiki
          - oapicf
          - pakkun
          - studio
