---
- hosts: macbookair01

  roles:

    # Required by ansible-role-studio-dev
    - role: gantsign.oh-my-zsh
      users:
        - username: cliffano
          oh_my_zsh:
            theme: bullet-train

    - role: geerlingguy.mac.mas
      mas_email: lookup('community.general.onepassword', 'MAS', section='username')
      mas_password: lookup('community.general.onepassword', 'MAS', section='username')
      mas_installed_apps:
        - { name: 1Password, id: 1511601750 }
        - { name: Brave Browser & Private Web, id: 1052879175 }
        - { name: Discord, id: 985746746 }
        - { name: Google Chrome, id: 535886823 }
        - { name: Firefox, id: 989804926 }
        - { name: WhatsApp Desktop, id: 1147396723 }
      mas_upgrade_all_apps: false

  tasks:

    - name: Provision Studio dev tools
      ansible.builtin.import_role:
        # name: cliffano.studio_dev
        name: ansible-role-studio-dev
      vars:
        sdev_username: cliffano
        sdev_home_dir: "{{ home }}"
        sdev_colima_networks:
          - konoha
          - onoki
        sdev_docker_images:
          - { id: 'studio', image: 'cliffano/studio', env_file: "{{ home }}/.env-docker-studio", home_dir: 'root', entrypoint: '/bin/bash' }
          - { id: 'kon-tiki', image: 'cliffano/kon-tiki', env_file: "{{ home }}/.env-docker-kon-tiki", home_dir: 'root', entrypoint: '/bin/bash' }
        sdev_gitconfig_link_src: "{{ home }}/dev/workspace-control/config/system-config/git/.gitconfig-{{ inventory_hostname }}"
        sdev_repoman_link_src: "{{ home }}/dev/workspace-control/config/workspace-config/repoman"
        sdev_ssh_configd_link_src: "{{ home }}/dev/workspace-control/config/system-config/ssh/{{ inventory_hostname }}.ssh_config"
        sdev_ssh_configd_file: "{{ inventory_hostname }}.ssh_config"
        sdev_ssh_config_link_src: "{{ home }}/dev/workspace-control/config/user-config/ssh/config"
        sdev_ssh_private_key_link_src: "{{ home }}/dev/workspace-control/config/user-config/ssh/konoha_id_rsa"
        sdev_ssh_public_key_link_src: "{{ home }}/dev/workspace-control/config/user-config/ssh/konoha_id_rsa.pub"
        sdev_sshkey_name: konoha_id_rsa
        sdev_vscode_workspaces:
          - ansible
          - code-generator
          - github-action
          - makefile
          - nodejs
          - oapicf
          - packer
          - python
        sdev_workspaces:
          - control
          - garage
          - g10
          - kon-tiki
          - oapicf
          - pakkun
          - studio

    - name: Provision Caesar III game
      ansible.builtin.import_role:
        # name: cliffano.caesar3
        name: ansible-role-caesar3
      vars:
        c3_gog_setup_version: '3_1.0.1.0_(76354)'
        c3_gog_setup_dir: "{{ home }}/files/caesar3"
        c3_install_dir: "{{ home }}/games/caesar3"
        c3_julius_app_version: '1.7.0'
