---
- hosts: macbookpro01

  roles:

    - role: geerlingguy.mac.mas
      mas_email: lookup('community.general.onepassword', 'MAS', section='username')
      mas_password: lookup('community.general.onepassword', 'MAS', section='password')
      mas_installed_apps:
        - { name: Google Chrome, id: 535886823 }
        - { name: iStat Menus, id: 1319778037 }
        - { name: Lungo, id: 1263070803 }
      mas_upgrade_all_apps: false

  tasks:

