---
- hosts: macbookpro02

  vars:
    homebrew_prefix: /opt/homebrew
    homebrew_installed_packages:
      - mas
      - node
      - packer
      - cloc
      - telnet
      - gpg2
      - pinentry-mac
      - gh
      - youtube-dl
      - jq
      - kubectl
    mas_email: { macappstore.user }
    mas_password: { macappstore.pass }
    mas_apps:
      - { name: Owly, id: 882812218 }
      - { name: Slack, id: 803453959 }
      - { name: WhatsApp Desktop, id: 1147396723 }
      - { name: Magnet, id: 441258766 }
      # - { name: 'iStat Menus', id: 1319778037 } # MDM blocks download
    docker_images:
      - { id: centos7, image: 'centos:centos7' }
      - { id: ubuntu, image: 'ubuntu' }
      - { id: aembuildenv, image: 'shinesolutions/aem-platform-buildenv' }
      - { id: theworksbuildenv, image: 'shinesolutions/the-works-buildenv' }
      - { id: theworksbuildenv-sandpit, image: 'ghcr.io/shinesolutions/the-works-buildenv-sandpit' }
      - { id: theworksbuildenv-publisher, image: 'ghcr.io/shinesolutions/the-works-buildenv-publisher' }
    main_workspaces:
      - control
    project_workspaces:
      - aoc
      - infracat
      - post
      - theworks
      - gatt
      - nlp
      - drup
      - vulscan
      - tels

  roles:
    # Required by ansible-role-studio-dev
    - role: gantsign.oh-my-zsh
      users:
        - username: cliffano
          oh_my_zsh:
            theme: bullet-train


  tasks:

    - name: Provision Studio dev tools
      ansible.builtin.import_role:
        # name: cliffano.studio_dev
        name: ansible-role-studio-dev
      vars:
        sdev_username: cliffano
        sdev_home_dir: "{{ home }}"
        sdev_colima_networks:
          - shn
        sdev_docker_images:
          - { id: 'aembuildenv', image: 'shinesolutions/aem-platform-buildenv', env_file: "{{ home }}/.env-docker-shn", home_dir: 'root', entrypoint: '/bin/bash' }
        sdev_gitconfig_link_src: "{{ home }}/dev/workspace-control/config-shn/system-config/git/.gitconfig-{{ inventory_hostname }}"
        sdev_repoman_link_src: "{{ home }}/dev/workspace-control/config-shn/workspace-config/repoman"
        sdev_ssh_configd_link_src: "{{ home }}/dev/workspace-control/config-shn/system-config/ssh/{{ inventory_hostname }}.ssh_config"
        sdev_ssh_configd_file: "{{ inventory_hostname }}.ssh_config"
        sdev_ssh_config_link_src: "{{ home }}/dev/workspace-control/config-shn/user-config/ssh/config"
        sdev_ssh_private_key_link_src: "{{ home }}/dev/workspace-control/config-shn/user-config/ssh/shn_id_rsa"
        sdev_ssh_public_key_link_src: "{{ home }}/dev/workspace-control/config-shn/user-config/ssh/shn_id_rsa.pub"
        sdev_ghostty_config_link_src: "{{ home }}/dev/workspace-control/config-shn/user-config/ghostty/config"
        sdev_tmux_config_link_src: "{{ home }}/dev/workspace-control/config-shn/user-config/tmux/.tmux.conf"
        sdev_tmux_layout_scripts_dir: "{{ home }}/dev/workspace-control/config-shn/workspace-config/tmux"
        sdev_tmux_layout_scripts:
          - aoc
        sdev_sshkey_name: shn_id_rsa
        sdev_vscode_workspaces:
          - aoc
        sdev_workspaces:
          - aoc
          - infracat
          - post
          - theworks
          - gatt
          - nlp
          - drup
          - vulscan
          - tels
        sdev_homebrew_packages_extra:
          - figlet
          - 1password-cli
          - cloc
          - telnet
          - gpg2
          - pinentry-mac
          - gh
          - jq
