---
- hosts: macbookair00

  roles:

    # - role: geerlingguy.mac.mas
    #   mas_email: lookup('community.general.onepassword', 'MAS_G10', section='username')
    #   mas_password: lookup('community.general.onepassword', 'MAS_G10', section='username')
    #   mas_installed_apps:
    #     - { name: Scratch, id: 1446785996 }
    #   mas_upgrade_all_apps: false

  tasks:

    - name: Provision Caesar III game
      ansible.builtin.import_role:
        # name: cliffano.caesar3
        name: ansible-role-caesar3
      vars:
        c3_gog_setup_version: '3_1.0.1.0_(76354)'
        c3_gog_setup_dir: "{{ home }}/files/caesar3"
        c3_install_dir: "{{ home }}/games/caesar3"
        c3_julius_app_version: '1.7.0'

    - name: Provision FabricMC Python VirtualEnv
      ansible.builtin.command:
        cmd: python3 -m venv {{ ansible_user_dir }}/.virtualenvs/fabricmc
        creates: "{{ ansible_user_dir }}/.virtualenvs/fabricmc"

    - name: Upgrade pip in FabricMC virtualenv
      ansible.builtin.command:
        cmd: "{{ ansible_user_dir }}/.virtualenvs/fabricmc/bin/pip install --upgrade pip"
      register: pip_upgrade
      changed_when: "'Successfully installed' in pip_upgrade.stdout"

    - name: Provision FabricMC Python dependencies
      ansible.builtin.command:
        cmd: "{{ ansible_user_dir }}/.virtualenvs/fabricmc/bin/pip install conflog modrinth-api-wrapper-pakkunbot==1.0.3 requests"
      register: pip_install
      changed_when: "'Successfully installed' in pip_install.stdout"

    - name: Provision FabricMC client
      ansible.builtin.import_role:
        # name: littlegodzillalaboratory.fabricmc
        name: ansible-role-fabricmc
      vars:
        fabmc_provision_server: false
        fabmc_provision_client: true
        fabmc_minecraft_version: '1.21.4'
        fabmc_installer_version: '1.0.1'
        fabmc_fabric_api_version: '0.119.4+1.21.4'
        fabmc_fabric_loader_version: '0.18.4'
        fabmc_client_dir: '{{ home_g10 }}/Library/Application Support/minecraft'
        fabmc_fabric_mods:
          # Performance
          - sodium
          - ferrite-core
          - lithium
          - immediatelyfast
          # Dependencies
          - architectury-api
          - balm
          - cardinal-components-api
          - cloth-config
          - collective
          - forge-config-api-port
          - lithostitched
          - modmenu
          - puzzles-lib
          - resourceful-lib
          - supermartijn642s-config-lib
          - yacl
          - yungs-api
          # Usability
          - bypass-fabric-check
          - durability-tooltip
          - xaeros-minimap
          - xaeros-world-map
          # Characters
          - crawl
          - bl4cks-sit
          - travelersbackpack
          - friends-and-foes
          - illager-invasion
          # Village
          - connectiblechains
          - trading-post
          - double-doors
          - animal_feeding_trough
          - ct-overhaul-village
          # World
          - waystones
          # Macaws Set
          - macaws-doors
          - macaws-furniture
          - macaws-paintings
          - macaws-stairs
          - macaws-roofs
          - macaws-bridges
          # Yungs Set
          - yungs-extras
          - yungs-bridges
          - yungs-better-strongholds
          - yungs-better-witch-huts
          - yungs-better-mineshafts
          - yungs-better-ocean-monuments
          - yungs-better-jungle-temples
          - yungs-better-nether-fortresses
        fabmc_fabric_mods_download_delay: 2
      environment:
        PATH: "{{ ansible_user_dir }}/.virtualenvs/fabricmc/bin:{{ ansible_env.PATH }}"
        VIRTUAL_ENV: "{{ ansible_user_dir }}/.virtualenvs/fabricmc"
      become: yes
      become_user: gio
