---
- hosts: macbookair01

  roles:

    # Required by ansible-role-studio-dev
    - role: gantsign.oh-my-zsh
      users:
        - username: cliffano
          oh_my_zsh:
            theme: bullet-train

    # TODO: Disabled MAS for now due to "No apps found in the Mac App Store for app ID" error
    # - role: geerlingguy.mac.mas
    #   mas_email: lookup('community.general.onepassword', 'MAS', section='username')
    #   mas_password: lookup('community.general.onepassword', 'MAS', section='password')
    #   mas_installed_apps:
    #     - { name: 1Password, id: 1511601750 }
    #     - { name: Brave Browser & Private Web, id: 1052879175 }
    #     - { name: Discord, id: 985746746 }
    #     - { name: Google Chrome, id: 535886823 }
    #     - { name: Firefox, id: 989804926 }
    #     - { name: iStat Menus, id: 1319778037 }
    #     - { name: Lungo, id: 1263070803 }
    #     - { name: WhatsApp Desktop, id: 1147396723 }
    #   mas_upgrade_all_apps: false

  tasks:

    - name: Provision Studio dev tools
      ansible.builtin.import_role:
        # name: cliffano.studio_dev
        name: ansible-role-studio-dev
      vars:
        sdev_username: cliffano
        sdev_home_dir: "{{ home }}"
        sdev_colima_networks:
          - konoha
          - onoki
        sdev_docker_images:
          - { id: 'base', image: 'cliffano/base', env_file: "{{ home }}/.env-docker-studio", home_dir: 'root', entrypoint: '/bin/bash' }
          - { id: 'control', image: 'cliffano/studio', env_file: "{{ home }}/.env-docker-control", home_dir: 'root', entrypoint: '/bin/bash' }
          - { id: 'studio', image: 'cliffano/studio', env_file: "{{ home }}/.env-docker-studio", home_dir: 'root', entrypoint: '/bin/bash' }
          - { id: 'kon-tiki', image: 'cliffano/kon-tiki', env_file: "{{ home }}/.env-docker-kon-tiki", home_dir: 'root', entrypoint: '/bin/bash' }
        sdev_gitconfig_link_src: "{{ home }}/dev/workspace-control/config/system-config/git/.gitconfig-{{ inventory_hostname }}"
        sdev_repoman_link_src: "{{ home }}/dev/workspace-control/config/workspace-config/repoman"
        sdev_ssh_configd_link_src: "{{ home }}/dev/workspace-control/config/system-config/ssh/{{ inventory_hostname }}.ssh_config"
        sdev_ssh_configd_file: "{{ inventory_hostname }}.ssh_config"
        sdev_ssh_config_link_src: "{{ home }}/dev/workspace-control/config/user-config/ssh/config"
        sdev_ssh_private_key_link_src: "{{ home }}/dev/workspace-control/config/user-config/ssh/konoha_id_rsa"
        sdev_ssh_public_key_link_src: "{{ home }}/dev/workspace-control/config/user-config/ssh/konoha_id_rsa.pub"
        sdev_ghostty_config_link_src: "{{ home }}/dev/workspace-control/config/user-config/ghostty/config"
        sdev_tmux_config_link_src: "{{ home }}/dev/workspace-control/config/user-config/tmux/.tmux.conf"
        sdev_tmux_layout_scripts_dir: "{{ home }}/dev/workspace-control/config/workspace-config/tmux"
        sdev_tmux_layout_scripts:
          - ansible
          - code-generator
          - control
          - github-action
          - kontiki818
          - littlegodzillalaboratory
          - makefile
          - mcp
          - node
          - oapicf
          - packer
          - python
        sdev_sshkey_name: konoha_id_rsa
        sdev_vscode_workspaces:
          - ansible
          - code-generator
          - control
          - github-action
          - makefile
          - mcp
          - nodejs
          - oapicf
          - packer
          - python
        sdev_workspaces:
          - aoc
          - contrib
          - control
          - garage
          - kon-tiki
          - littlegodzillalaboratory
          - oapicf
          - pakkun
        sdev_homebrew_packages_extra:
          - fdupes
          - figlet
          - ripgrep
          - 1password-cli

    - name: Provision Caesar III game
      ansible.builtin.import_role:
        # name: cliffano.caesar3
        name: ansible-role-caesar3
      vars:
        c3_gog_setup_version: '3_1.0.1.0_(76354)'
        c3_gog_setup_dir: "{{ home }}/files/caesar3"
        c3_install_dir: "{{ home }}/games/caesar3"
        c3_julius_app_version: '1.7.0'

    - name: Provision FabricMC Python VirtualEnv
      ansible.builtin.command:
        cmd: python3 -m venv {{ ansible_facts['user_dir'] }}/.virtualenvs/fabricmc
        creates: "{{ ansible_facts['user_dir'] }}/.virtualenvs/fabricmc"

    - name: Provision FabricMC Python dependencies
      ansible.builtin.command:
        cmd: "{{ ansible_facts['user_dir'] }}/.virtualenvs/fabricmc/bin/pip install conflog modrinth-api-wrapper requests"
      register: pip_install
      changed_when: "'Successfully installed' in pip_install.stdout"

    - name: Provision FabricMC client
      ansible.builtin.import_role:
        # name: littlegodzillalaboratory.fabricmc
        name: ansible-role-fabricmc
      vars:
        fabmc_provision_server: false
        fabmc_provision_client: true
        fabmc_minecraft_version: '1.21.4'
        fabmc_installer_version: '1.0.1'
        fabmc_fabric_api_version: '0.119.4+1.21.4'
        fabmc_fabric_loader_version: '0.18.4'
        fabmc_client_dir: '{{ home }}/Library/Application Support/minecraft'
        fabmc_fabric_mods:
          # Performance
          - sodium
          - ferrite-core
          - lithium
          - immediatelyfast
          # Dependencies
          - architectury-api
          - balm
          - cardinal-components-api
          - cloth-config
          - collective
          - forge-config-api-port
          - lithostitched
          - modmenu
          - puzzles-lib
          - resourceful-lib
          - supermartijn642s-config-lib
          - yacl
          - yungs-api
          # Usability
          - bypass-fabric-check
          - durability-tooltip
          - xaeros-minimap
          - xaeros-world-map
          # Characters
          - crawl
          - bl4cks-sit
          - friends-and-foes
          - illager-invasion
          # Village
          - connectiblechains
          - trading-post
          - double-doors
          - animal_feeding_trough
          - ct-overhaul-village
          # World
          - waystones
          # Macaws Set
          - macaws-doors
          - macaws-furniture
          - macaws-paintings
          - macaws-stairs
          - macaws-roofs
          - macaws-bridges
          # Yungs Set
          - yungs-extras
          - yungs-bridges
          - yungs-better-strongholds
          - yungs-better-witch-huts
          - yungs-better-mineshafts
          - yungs-better-ocean-monuments
          - yungs-better-jungle-temples
          - yungs-better-nether-fortresses
        fabmc_fabric_mods_download_delay: 2
      environment:
        PATH: "{{ ansible_facts['user_dir'] }}/.virtualenvs/fabricmc/bin:{{ ansible_facts['env']['PATH'] }}"
        VIRTUAL_ENV: "{{ ansible_facts['user_dir'] }}/.virtualenvs/fabricmc"
