---
- hosts: macmini00

  tasks:

  - name: Ensure dev directory exists
    file: path="{{ home }}/dev/" state=directory mode=0755

  - name: Ensure Jenkins home directory exists
    file: path="{{ home }}/dev/jenkins-home" state=directory mode=0755

  - name: Ensure Jenkins backup directory exists
    file: path="{{ home }}/dev/jenkins-backup" state=directory mode=0755

  - name: Ensure Jenkins can write log file
    file: path="/var/log/" state=directory mode=0777
    become: yes

  - name: Ensure jenkins-workspace repo is cloned
    ansible.builtin.git:
      repo: 'https://github.com/cliffano/jenkins-workspace'
      dest: "{{ home }}/dev/jenkins-workspace/"
      clone: yes
      update: yes

  - name: Set aliases for Jenkins
    lineinfile: dest={{ home }}/.bashrc line="{{ item }}" state=present backup=no
    with_items:
      - alias jenkins-start='cd {{ home }}/dev/jenkins-workspace/ && JENKINS_HOME={{ home }}/dev/jenkins-home/ nohup make jenkins-start-sans-home > /var/log/jenkins.log &'
      - alias jenkins-stop='pkill java'

  - name: Install nvm
    ansible.builtin.shell: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash

  - name: Install node
    ansible.builtin.shell: source ~/.bashrc && nvm ls && nvm install v16

  - name: Install npm packages
    ansible.builtin.shell: source ~/.bashrc && nvm use v16 && npm install -g open-sesame@latest

  - name: Ensure AWS config dir is provisioned
    ansible.builtin.file:
      path: ~/.aws/
      state: directory
      mode: '0755'

  - name: Ensure AWS credentials file is provisioned
    ansible.builtin.file:
      path: ~/.aws/credentials
      state: touch
      mode: '0644'