---
- hosts: macmini00

  tasks:

  - name: Ensure dev directory exists
    file: path="{{ home }}/dev/" state=directory mode=0755

  - name: Ensure Jenkins home directory exists
    file: path="{{ home }}/dev/jenkins-home" state=directory mode=0755

  - name: Ensure jenkins-workspace repo is cloned
    ansible.builtin.git:
      repo: 'https://github.com/cliffano/jenkins-workspace'
      dest: "{{ home }}/dev/jenkins-workspace/"
      clone: yes
      update: yes

  - name: Set aliases for Jenkins
    lineinfile: dest={{ home }}/.bashrc line="{{ item }}" state=present backup=no
    with_items:
      - alias jenkins-start='cd {{ home }}/dev/jenkins-workspace/ && JENKINS_HOME={{ home }}/dev/jenkins-home/ make jenkins-start-sans-home &'
