---
- hosts: workstation

  vars:
    homebrew_install_path: /usr/local/homebrew
    homebrew_installed_packages:
      - packer
      - awscli
    homebrew_taps:
      - caskroom/cask
      - caskroom/versions
      - homebrew/binary
    homebrew_cask_apps:
      - atom
    rvm1_install_flags: '--user-install'
    sdkman_dir: /usr/local/sdkman
    sdkman_auto_answer: true
    sdkman_update: true
    sdkman_install_packages:
      - { candidate: maven, version: 3.5.0 }
      - { candidate: maven, version: 3.3.9 }
    sdkman_defaults:
      maven: 3.5.0
    sdkman_flush_caches_before:
      - temp
    sdkman_flush_caches_after:
      - archives
      - broadcast
      - candidates
      - temp

  roles:
    - { role: rvm_io.rvm1-ruby }
    - { role: Comcast.sdkman }

  tasks:

  - name: Ensure global npm packages are installed
    npm: name="{{item}}" global=yes state=present
    items:
      - repoman
