---
- hosts: raspberrypi00

  tasks:

  - name: Ensure dev directory exists
    file: path=/home/pi/dev/ state=directory mode=0755

  - name: Ensure Home Assistant home directory exists
    file: path=/home/pi/dev/hass-home/ state=directory mode=0755

  - name: Ensure requirement packages are installed
    apt: name={{ item }} state=present  update_cache=yes
    become: yes
    with_items:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      - python3-pip

  - name: Install Python packages
    pip:
      name: "{{ item }}"
      executable: pip3
    with_items:
      - docker

  # - name: Add Docker’s official GPG key
  #   ansible.builtin.shell: curl -fsSL https://download.docker.com/linux/debian/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

  - name: Set up Docker stable repository
    ansible.builtin.shell: echo "deb [arch=armhf signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

  - name: Update apt package index
    become: yes
    ansible.builtin.shell: apt-get update

  - name: Ensure Docker Engine and containerd packages are installed
    apt: name={{ item }} state=present  update_cache=yes
    become: yes
    with_items:
      - docker-ce
      - docker-ce-cli
      - containerd.io

  - name: Pull Home Assistant Docker image (temporary until issue with Python interpreter not seeing docker module is solved)
    become: yes
    ansible.builtin.shell: docker pull homeassistant/raspberrypi2-homeassistant

  # # Commented out due to an issue with Python interpreter not seeing docker module even though pip3 list shows docker 5.0.2 is already installed
  # # Note: python3 is confirmed to definitely be used as Ansible's Python interpreter on the host
  # - name: Pull Home Assistant Docker image
  #   become: yes
  #   community.docker.docker_image:
  #     name: homeassistant/raspberrypi2-homeassistant
  #     source: pull

  - name: Set aliases for Home Assistant
    lineinfile: dest={{ home }}/.profile line="{{ item }}" state=present backup=no
    with_items:
      - alias suhass='sudo docker run --init -d --name="home-assistant" --privileged -e "TZ=Australia/Melbourne" -v /home/pi/dev/hass-home:/config -p 8123:8123 homeassistant/raspberrypi2-homeassistant:latest'
