---
- hosts: raspberrypi00

  # roles:
    # - role: leonidas.nvm
    #   nvm:
    #     user: jenkins
    #     version: v0.28.0
    #     node_version: '4'
    #   sudo: yes
    # - { role: cliffano.newrelic-unix }

  tasks:

  # - name: Ensure opt directory allows cliffano.newrelic-unix to create plugins directory
  #   sudo: yes
  #   file: path=/opt/ state=directory mode=0777

  - name: Ensure old Sendman configuration for GD hosts are removed
    file: path=/var/lib/jenkins/.ssh/{{ item }}.json state=absent
    with_items:
      - deidara
      - kakuzu
      - kisame
      - suna

  - name: Comment out inactive Collabora sources list
    become: yes
    copy: content="#deb http://raspberrypi.collabora.com wheezy rpi\n" dest=/etc/apt/sources.list.d/collabora.list

  - name: Comment out inactive Raspi sources list
    become: yes
    copy: content="#deb http://archive.raspberrypi.org/debian/ wheezy main\n#deb-src http://archive.raspberrypi.org/debian/ wheezy main\n" dest=/etc/apt/sources.list.d/raspi.list

  - name: Set AARNet as singular sources list
    become: yes
    copy: content="deb http://mirror.aarnet.edu.au/pub/raspbian/raspbian jessie main contrib non-free rpi\n" dest=/etc/apt/sources.list

  - name: Ensure os packages are installed
    apt: name={{ item }} state=present  update_cache=yes
    become: yes
    with_items:
      - openssl
      - build-essential
      - libreadline-gplv2-dev
      - libc6-dev
      - tk-dev
      - libncurses5-dev
      - libncursesw5-dev
      - libreadline6-dev
      - libdb5.3-dev
      - libgdbm-dev
      - libsqlite3-dev
      - libssl-dev
      - libbz2-dev
      - libexpat1-dev
      - liblzma-dev
      - zlib1g-dev
      - libffi-dev
      - libjpeg-dev
      - libopenjp2-7
      - libtiff5
      - jenkins
      - dh-autoreconf
      - python3
      - python3-pip
      - python3-dev
      - python3-venv
      - autoconf 

  - name: Ensure homeassistant user is created
    become: yes
    user:
      name: homeassistant
      shell: /bin/bash
      groups: dialout,gpio
      create_home: True

  - name: Ensure srv dir is created
    become: yes
    file:
      path: /srv
      state: directory
      mode: '0755'

  - name: Ensure homeassistant dir is created
    become: yes
    file:
      path: /srv/homeassistant
      state: directory
      owner: homeassistant
      group: homeassistant
      mode: '0755'

  - name: Ensure Python packages are installed
    become: yes
    pip:
      name: homeassistant
      executable: pip3.8