---
- hosts: raspberrypi01

  vars:
    nvm_node_version: "16.17.0"
    nvm_user_name: cliffano
    nvm_install_globally: ['nestor-buildlight']
    minecraft_version: '1.21.1'
    install_dir: "{{ home }}/games/minecraft"
    java_opts: -Xmx2048M -Xms1024M

  roles:
    - cliffano.minecraft_java
  #   - { role: grzegorznowak.nvm_node, become: yes }

  tasks:

  - name: Ensure games directory exists
    file: path="{{ home }}/games/" state=directory mode=0755

  - name: Set aliases for Minecraft
    lineinfile: dest="{{ home }}/.profile" line="{{ item }}" state=present backup=no
    loop:
      - alias minecraft-start='cd {{ home }}/games/minecraft/workspace && nohup {{ home }}/games/minecraft/bin/start.sh > /var/log/minecraft/minecraft.log &'
      - alias minecraft-stop='pkill java'
      - alias minecraft-conf='vi {{ home }}/games/minecraft/workspace/server.properties'
      - alias minecraft-log='tail -f {{ home }}/games/minecraft/workspace/logs/latest.log'