---
- hosts: raspberrypi00

  # roles:
    # - role: leonidas.nvm
    #   nvm:
    #     user: jenkins
    #     version: v0.28.0
    #     node_version: '4'
    #   sudo: yes
    # - { role: cliffano.newrelic-unix }

  tasks:

  # - name: Ensure opt directory allows cliffano.newrelic-unix to create plugins directory
  #   sudo: yes
  #   file: path=/opt/ state=directory mode=0777

  - name: Ensure os packages are installed
    apt: name={{ item }} state=present
    with_items:
      - jenkins
      - dh-autoreconf

  - name: Ensure old Sendman configuration for GD hosts are removed
    file: path=/var/lib/jenkins/.ssh/{{ item }}.json state=absent
    with_items:
      - deidara
      - kakuzu
      - kisame
      - suna
