---
- hosts: raspberrypi02

  vars:
    os_user: cliffano
    os_group: cliffano

  roles:
    - role: Comcast.sdkman
      sdkman_install_packages:
        - { candidate: java, version: 21-tem }

  tasks:

  - name: Ensure games directory exists
    ansible.builtin.file:
      path: "{{ home }}/games/"
      state: directory
      mode: '0755'

  - name: Ensure game log directories exist
    ansible.builtin.file:
      path: "/var/log/{{ item }}/"
      state: directory
      mode: '0755'
      owner: "{{ os_user }}"
      group: "{{ os_group }}"
    become: yes
    loop:
      - fabricmc
      - minecraft-waterland

  - name: Provision Minecraft Java
    ansible.builtin.import_role:
      # name: littlegodzillalaboratory.minecraft_java
      name: ansible-role-minecraft-java
    vars:
      mcj_minecraft_version: '1.21.10'
      mcj_install_id: minecraft-waterland
      mcj_install_dir: "{{ home }}/games/minecraft-waterland"
      mcj_os_user: cliffano
      mcj_env_path: /home/cliffano/.sdkman/candidates/java/current/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games
      mcj_java_opts: -Xmx2048M -Xms1024M
      mcj_server_properties:
        difficulty: normal
        gamemode: survival
        hardcore: "false"
        max-players: 10
        motd: "Welcome to Waterland!"
        online-mode: "false"
        pvp: "false"
        query.port: 25565
        server-port: 25565
        
  - name: Provision FabricMC
    ansible.builtin.import_role:
      # name: littlegodzillalaboratory.fabricmc
      name: ansible-role-fabricmc
    vars:
      fabmc_minecraft_version: '1.21.4'
      fabmc_fabric_loader_version: '0.16.10'
      fabmc_installer_version: '1.0.1'
      fabmc_install_id: minecraft-exploration
      fabmc_install_dir: "{{ home }}/games/minecraft-exploration"
      fabmc_os_user: cliffano
      fabmc_env_path: /home/cliffano/.sdkman/candidates/java/current/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games
      fabmc_java_opts: -Xmx2048M -Xms1024M
      fabmc_server_properties:
        difficulty: easy
        gamemode: survival
        hardcore: "false"
        max-players: 10
        motd: "Explore the world of moddable Minecraft!"
        online-mode: "false"
        pvp: "false"
        query.port: 25665
        server-port: 25665
        rcon.port: 25675
