---
- hosts: raspberrypi00
  gather_facts: yes

  tasks:

    - name: Provision Pi-hole
      ansible.builtin.import_role:
        # name: drew1kun.pihole
        name: ansible-role-pihole
      vars:
        pihole_setupVars_conf_WEBPASSWD: "{{ pihole_web_password }}"

