---
- hosts: raspberrypi01

  vars:
    os_user: cliffano
    os_group: cliffano
    nvm_node_version: "16.17.0"
    nvm_user_name: cliffano
    nvm_install_globally: ['nestor-buildlight']
    fabmc_minecraft_version: '1.21.4'
    fabmc_fabric_loader_version: '0.16.10'
    fabmc_installer_version: '1.0.1'
    fabmc_install_dir: "{{ home }}/games/fabricmc"
    fabmc_java_opts: -Xmx2048M -Xms1024M

  roles:
    # - cliffano.fabricmc
  #   - { role: grzegorznowak.nvm_node, become: yes }

  tasks:

  - name: Ensure games directory exists
    ansible.builtin.file:
      path: "{{ home }}/games/"
      state: directory
      mode: '0755'

  - name: Ensure game log directories exist
    ansible.builtin.file:
      path: "/var/log/{{ item }}/"
      state: directory
      mode: '0755'
      owner: "{{ os_user }}"
      group: "{{ os_group }}"
    become: yes
    loop:
      - fabricmc
      - minecraft

  - name: Provision Minecraft Java
    ansible.builtin.import_role:
      name: cliffano.minecraft_java
    vars:
      mcj_minecraft_version: '1.21.4'
      mcj_install_dir: "{{ home }}/games/minecraft"
      mcj_java_opts: -Xmx2048M -Xms1024M

  - name: Set aliases for FabricMC
    ansible.builtin.lineinfile:
      path: "{{ home }}/.profile"
      state: present
      backup: no
      line: "{{ item }}"
    loop:
      - alias fabricmc-start='cd {{ home }}/games/fabricmc/workspace && nohup {{ home }}/games/fabricmc/bin/start.sh > /var/log/fabricmc/fabricmc.log &'
      - alias fabricmc-stop='pkill java'
      - alias fabricmc-conf='vi {{ home }}/games/fabricmc/workspace/server.properties'
      - alias fabricmc-log='tail -f {{ home }}/games/fabricmc/workspace/logs/latest.log'

  - name: Set aliases for Minecraft Java
    ansible.builtin.lineinfile:
      path: "{{ home }}/.profile"
      state: present
      backup: no
      line: "{{ item }}"
    loop:
      - alias minecraft-start='cd {{ home }}/games/minecraft/workspace && nohup {{ home }}/games/minecraft/bin/start.sh > /var/log/minecraft/minecraft.log &'
      - alias minecraft-stop='pkill java'
      - alias minecraft-conf='vi {{ home }}/games/minecraft/workspace/server.properties'
      - alias minecraft-log='tail -f {{ home }}/games/minecraft/workspace/logs/latest.log'