---
- hosts: raspberrypi01

  vars:
    nvm_node_version: "16.17.0"
    nvm_user_name: cliffano
    nvm_install_globally: ['nestor-buildlight']

  roles:
  #   - { role: grzegorznowak.nvm_node, become: yes }
    - role: Comcast.sdkman
      sdkman_install_packages:
        - { candidate: java, version: 21.0.8-librca }
    - role: geerlingguy.jenkins
      become: yes
      jenkins_version: "2.463"

  tasks:

    - name: Create symlink for using SDKMAN Java as local Java
      ansible.builtin.file:
        src: /home/cliffano/.sdkman/candidates/java/current/bin/java
        dest: /usr/local/bin/java
        state: link
      become: yes