---
- hosts: studio

  vars:
    orgs:
      - studio
      - shine
    homebrew_installed_packages:
      - mas
      - node
      - packer
    mas_email: { macappstore.user }
    mas_password: { macappstore.pass }
    mas_apps:
      - { name: DMesh, id: 480992638 }
      - { name: Owly, id: 882812218 }
      - { name: Pixelmator, id: 407963104 }
      - { name: Slack, id: 803453959 }
      - { name: WhatsApp Desktop, id: 1147396723 }
    docker_images:
      - { id: kontiki, image: 'cliffano/kon-tiki-cred' }
      - { id: studio, image: 'cliffano/studio' }
      - { id: swaggyc, image: 'cliffano/swaggy-c' }
      - { id: centos7, image: 'centos:centos7' }
      - { id: ubuntu, image: 'ubuntu' }
      - { id: aembuildenv, image: 'shinesolutions/aem-platform-buildenv-publisher' }

  roles:
    # - role: geerlingguy.homebrew
    # - role: rkhmelichek.mas

  tasks:

  - name: Ensure SSH directory exists
    file: path={{ home }}/.ssh/ state=directory

  - name: Ensure SSH config directory exists
    file: path={{ home }}/.ssh/config.d/ state=directory

  - name: Set SSH configuration
    file: src={{ home }}/dev/workspace-studio/config/ssh/{{ item }} dest={{ home }}/.ssh/{{ item }} state=link
    with_items:
      - config
      - konoha_id_rsa
      - konoha_id_rsa.pub

  - name: Set SSH configuration include
    file: src={{ home }}/dev/workspace-studio/config/{{ item }}/.ssh_config dest={{ home }}/.ssh/config.d/config-{{ item }} state=link
    with_items: "{{ orgs }}"

  - name: Ensure .profile file exists
    file: path={{ home }}/.profile state=touch mode=0644

  - name: Set basic aliases
    lineinfile: dest={{ home }}/.profile line="{{ item }}" state=present backup=yes
    with_items:
      - alias lessr='less -R'

  - name: Set GitHub aliases
    lineinfile: dest={{ home }}/.profile line="{{ item }}" state=present backup=yes
    with_items:
      - alias gaa='git add -A'
      - alias gca='git commit -am'
      - alias gcp='git cherry-pick'
      - alias gcpc='git cherry-pick --continue'
      - alias gd='git diff'
      - alias gl5='git log -5'
      - alias gp='git push'
      - alias gpr='git pull --rebase'
      - alias gpt='git push --tags'
      - alias gprp='git pull --rebase && git push'
      - alias gprpt='git pull --rebase && git push && git push --tags'
      - alias grh='git reset HEAD~'
      - alias grc='git rebase --continue'
      - alias gs='git status'
      - alias gsa='git stash apply'
      - alias gta='git tag -a'

  - name: Set Docker aliases
    lineinfile: dest={{ home }}/.profile line="{{ item }}" state=present backup=yes
    with_items:
      - alias dsa='docker stop $(docker ps -a -q)'
      - alias dra='docker rm $(docker ps -a -q)'
      - alias dia='docker rmi $(docker images -q --filter "dangling=true")'
      - alias dxt='docker exec -it'

  - name: Set OpenSesame aliases
    lineinfile: dest={{ home }}/.profile line="alias osa='open-sesame aws --region ap-southeast-2 --secgroup-id {{ opensesame_secgroups }} --port 22 --name cliffs'" state=present backup=yes

  - name: Set Docker run aliases
    lineinfile: dest={{ home }}/.profile regexp="alias drn-{{ item.id }}.+" line="alias drn-{{ item.id }}='docker run --name {{ item.id }} --workdir /opt/workspace -v /var/run/docker.sock:/var/run/docker.sock -v `pwd`:/opt/workspace -i -t {{ item.image }}'" state=present backup=yes
    with_items: "{{ docker_images }}"

  - name: Set Docker attach aliases
    lineinfile: dest={{ home }}/.profile line="alias dxt-{{ item.id }}='docker exec -it {{ item.id }}'" state=present backup=yes
    with_items: "{{ docker_images }}"

  - name: Set Docker one-off aliases
    lineinfile: dest={{ home }}/.profile line="alias drno-{{ item.id }}='docker run --rm --workdir /opt/workspace -v /var/run/docker.sock:/var/run/docker.sock -v `pwd`:/opt/workspace -i -t {{ item.image }}'" state=present backup=yes
    with_items: "{{ docker_images }}"

  - name: Set Docker AEM Platform one-off alias
    lineinfile: dest={{ home }}/.profile line="alias drno-aem-workspace='docker run --rm --workdir /opt/workspace -v /var/run/docker.sock:/var/run/docker.sock -v `pwd`:/opt/workspace -p 45600-45700:45600-45700/tcp -i -t shinesolutions/aem-platform-buildenv-publisher'" state=present backup=yes

  - name: Set Jenkins alias
    lineinfile: dest={{ home }}/.profile line="alias jenkins='docker run -p 8080:8080 -p 50000:50000 -v {{ home }}/dev/workspace-orgs/jenkins_home:/var/jenkins_home jenkins/jenkins:lts'" state=present backup=yes

  - name: Set Studio workspace aliases
    lineinfile: dest={{ home }}/.profile line="alias ws-{{ item }}='cd {{ home }}/dev/workspace-{{ item }}/ && repoman get'" state=present backup=yes
    with_items: "{{ orgs }}"

  - name: Set Makefile .PHONY creator alias
    lineinfile: dest={{ home }}/.profile line="alias makephony='grep \'^[^#[:space:]].*:\' Makefile | sed -e \"s/:.*$//\" | paste -s -d\" \" - | sed -e \"s/\.PHONY$//\"'" state=present backup=yes

  - name: Ensure global node.js packages are installed
    npm: name="{{item}}" global=yes state=present
    with_items:
      - repoman
      - open-sesame
      - nba-go

  - name: Ensure workspace directories exist
    file: path={{ home }}/dev/workspace-{{ item }} state=directory mode=0755
    with_items: "{{ orgs }}"

  - name: Set Repoman configuration for workspace repositories
    file: src={{ home }}/dev/workspace-studio/config/{{ item }}/.repoman.json dest={{ home }}/dev/workspace-{{ item }}/.repoman.json state=link
    with_items: "{{ orgs }}"

  - name: Ensure iTerm2 scripts directory exists
    file: path='{{ home }}/Library/Application Support/iTerm2/Scripts/' state=directory

  - name: Set iTerm2 init script
    file: src={{ home }}/dev/workspace-studio/ryokan/resources/studio/iterm2-init.app dest='{{ home }}/Library/Application Support/iTerm2/Scripts/iterm2-init.app' state=link

  - name: Pull Docker images
    docker_image:
      name: "{{ item }}"
    with_items:
      - cliffano/kon-tiki
      - cliffano/studio
      - cliffano/swaggy-c
      - centos:centos7
      - ubuntu
      - jenkins/jenkins:lts
      - node
