---
- hosts: util

  vars:
    foo: bar

  roles:
    - { role: andrewrothstein.packer, become: yes, packer_ver: 1.0.0, packer_checksum: "md5:7b4adb98454fbfff7ef673245d345293" }
    - { role: cliffano.newrelic-unix, become: yes }

  tasks:

  - package:
      name: "{{ item }}"
      state: latest
    become: yes
    with_items:
      - git
      - docker

  - name: Set ec2-user .bashrc
    lineinfile: dest={{ home }}/.bashrc line="{{ item }}" state=present backup=yes
    with_items:
      - alias gaa='git add -A'
      - alias gd='git diff'
      - alias gs='git status'
      - alias gpr='git pull --rebase'
      - alias gpt='git push --tags'
      - alias gprp='git pull --rebase && git push'
      - alias grh='git reset HEAD~'
      - alias dsa='sudo docker stop $(sudo docker ps -a -q)'
      - alias dra='sudo docker rm $(sudo docker ps -a -q)'
      - alias dia='sudo docker rmi $(sudo docker images -q --filter "dangling=true")'
      - alias drn='sudo docker run --workdir /opt/workspace -v `pwd`:/opt/workspace -t cliffano/swaggy-c'

  - name: Set root .bashrc
    become: yes
    lineinfile: dest=/root/.bashrc line="{{ item }}" state=present backup=yes
    with_items:
      - alias dsa='sudo docker stop $(sudo docker ps -a -q)'
      - alias dra='sudo docker rm $(sudo docker ps -a -q)'

  - name: Ensure required gems are installed
    gem:
      name: "{{ item.name }}"
      version: "{{ item.version }}"
      state: present
    with_items:
      - { name: puppet_forge, version: 2.2.4 }
      - { name: r10k, version: 2.5.5 }

  - name: Ensure dev directory exists
    file: path={{ home }}/dev/ state=directory

  - name: Ensure workspace directory exists
    file: path={{ home }}/dev/workspace/ state=directory

  - name: Ensure repos are cloned
    git:
      repo: "https://github.com/cliffano/{{ item }}.git"
      dest: "{{ home }}/dev/workspace/{{ item }}"
      update: no
    with_items:
      - packer-swaggy-c
      - swaggy-jenkins
