---
- hosts: util

  roles:
    - { role: andrewrothstein.packer, become: yes, packer_ver: 1.0.2, packer_checksum: "md5:9f190daf0e42b52c1f2a186b73f90060" }
    - { role: cliffano.newrelic-unix, become: yes }

  tasks:

  - package:
      name: "{{ item }}"
      state: latest
    become: yes
    with_items:
      - git
      - docker
      - java-1.8.0-openjdk

  - package:
      name: "{{ item }}"
      state: absent
    become: yes
    with_items:
      - java-1.6.0-openjdk
      - java-1.7.0-openjdk

  - rpm_key:
      state: present
      key: https://jenkins-ci.org/redhat/jenkins-ci.org.key
    become: yes
  - name: Add Jenkins repo
    shell: wget -O /etc/yum.repos.d/jenkins.repo http://pkg.jenkins-ci.org/redhat/jenkins.repo
    become: yes
  - package:
      name: jenkins
      state: installed
    become: yes

  - name: Set ec2-user .bashrc
    lineinfile: dest={{ home }}/.bashrc line="{{ item }}" state=present backup=yes
    with_items:
      - alias gaa='git add -A'
      - alias gd='git diff'
      - alias gs='git status'
      - alias gpr='git pull --rebase'
      - alias gpt='git push --tags'
      - alias gprp='git pull --rebase && git push'
      - alias grh='git reset HEAD~'
      - alias dsa='sudo docker stop $(sudo docker ps -a -q)'
      - alias dra='sudo docker rm $(sudo docker ps -a -q)'
      - alias dia='sudo docker rmi $(sudo docker images -q --filter "dangling=true")'
      - alias drn='sudo docker run --workdir /opt/workspace -v `pwd`:/opt/workspace -t cliffano/swaggy-c'

  - name: Set root .bashrc
    become: yes
    lineinfile: dest=/root/.bashrc line="{{ item }}" state=present backup=yes
    with_items:
      - alias gaa='git add -A'
      - alias gd='git diff'
      - alias gs='git status'
      - alias gpr='git pull --rebase'
      - alias gpt='git push --tags'
      - alias gprp='git pull --rebase && git push'
      - alias grh='git reset HEAD~'
      - alias dsa='docker stop $(docker ps -a -q)'
      - alias dra='docker rm $(docker ps -a -q)'
      - alias dia='docker rmi $(docker images -q --filter "dangling=true")'
      - alias drn='docker run --workdir /opt/workspace -v `pwd`:/opt/workspace -t cliffano/swaggy-c'

  - name: Ensure required gems are installed
    gem:
      name: "{{ item.name }}"
      version: "{{ item.version }}"
      state: present
    with_items:
      - { name: puppet_forge, version: 2.2.4 }
      - { name: r10k, version: 2.5.5 }

  - name: Ensure dev directory exists
    file: path={{ home }}/dev/ state=directory

  - name: Ensure workspace directory exists
    file: path={{ home }}/dev/workspace/ state=directory

  - name: Ensure repos are cloned
    git:
      repo: "https://github.com/cliffano/{{ item }}.git"
      dest: "{{ home }}/dev/workspace/{{ item }}"
      update: no
    with_items:
      - packer-swaggy-c
      - swaggy-jenkins
