---
- hosts: web

  roles:
    # - role: ansible-role-droplet-docker
    - role: cliffano.droplet-docker
    - { role: Rackspace_Automation.newrelic, newrelic_license_key: '{{ newrelic_license_key }}' }

  tasks:

  - name: Ensure os packages are installed
    apt: name={{ item }} state=present
    with_items:
      - nginx
      - sysdig

  - name: Ensure applications base directory exists
    file: name=/app/{{ item.name }} state=directory
    with_items: sites

  - name: Ensure application stage directory exists
    file: name=/app/{{ item.name }}/stage state=directory
    with_items: sites

  - name: Ensure application configuration directory exists
    file: name=/app/{{ item.name }}/conf state=directory
    with_items: sites

  - name: Ensure application data directory exists
    file: name=/app/{{ item.name }}/data state=directory
    with_items: sites

  - name: Ensure application logs directory exists
    file: name=/app/{{ item.name }}/logs state=directory
    with_items: sites

  - name: Download applications
    git: repo=git://github.com/cliffano/{{ item.name }}.git dest=/app/{{ item.name }}/stage accept_hostkey=yes
    with_items: sites

  - name: Set application configuration
    template: src=../resources/ute/ute.json dest=/app/{{ item.name }}/conf/ute.json
    with_items: sites

  - name: Set application logging configuration
    template: src=../resources/ute/log4js.json dest=/app/{{ item.name }}/conf/log4js.json
    with_items: sites

  - name: Set feedpaper feeds file
    template: src=../resources/feedpaper/feeds.json dest=/app/{{ item.name }}/data/feeds.json
    with_items: sites

  - name: Set nginx configuration
    template: src=../resources/nginx/site dest=/etc/nginx/sites-enabled/{{ item.host_name }}
    with_items: sites

  - name: Set docker build aliases
    lineinfile: dest={{ home }}/.profile regexp='^alias docker-build-{{ item.name }}.*' line="alias docker-build-{{ item.name }}='docker build -t {{ item.name }} .'" state=present backup=yes
    with_items: sites

  - name: Set docker run aliases
    lineinfile: dest={{ home }}/.profile regexp='^alias docker-run-{{ item.name }}.*' line="alias docker-run-{{ item.name }}='docker run --name {{ item.name }} -p 127.0.0.1:{{ item.port }}:{{ item.port }}  -v /app/{{ item.name }}/conf/ute.json:/app/conf/ute.json -v /app/{{ item.name }}/conf/log4js.json:/app/conf/log4js.json -v /app/{{ item.name }}/data/feeds.json:/app/data/feeds.json -v /app/{{ item.name }}/logs/:/app/logs/ -i -d -t {{ item.name }}'" state=present backup=yes
    with_items: sites
