---
- hosts: web

  roles:
    # - role: cliffano.droplet-docker
    - role: ansible-role-droplet-docker

  tasks:

  - name: Ensure nginx is installed
    apt: name=nginx state=present

  - name: Ensure applications base directory exists
    file: name=/app state=directory

  - name: Ensure data base directory exists
    file: name=/app/data state=directory

  - name: Ensure app data directory exists
    file: name=/app/data/{{ item.name }} state=directory
    with_items: sites

  - name: Ensure logs base directory exists
    file: name=/app/logs state=directory

  - name: Ensure app log directory exists
    file: name=/app/logs/{{ item.name }} state=directory
    with_items: sites

  - name: Download applications
    git: repo=git://github.com/cliffano/{{ item.name }}.git dest=/app/{{ item.name }} accept_hostkey=yes
    with_items: sites

  - name: Set nginx configuration
    template: src=../resources/nginx/site dest=/etc/nginx/sites-enabled/{{ item.host_name }}
    with_items: sites

  - name: Set docker build aliases
    lineinfile: dest={{ home }}/.profile line="alias docker-build-{{ item.name }}='docker build -t {{ item.name }} .'" state=present backup=yes
    with_items: sites

  - name: Set docker run aliases
    lineinfile: dest={{ home }}/.profile line="alias docker-run-{{ item.name }}='docker run --name {{ item.name }} -p 127.0.0.1:{{ item.port }}:{{ item.port }}  -e "UTE_ENV=uat" -v /app/logs/{{ item.name }}/:/var/log/ -v /app/data/{{ item.name }}/:/app/data/ -i -d -t {{ item.name }}'" state=present backup=yes
    with_items: sites
