---
- hosts: workstation

  vars:
    homebrew_install_path: /usr/local/homebrew
    homebrew_installed_packages:
      - xz
      - wget
      - imagemagick
      - sysdig
      - gpg
      - brew-cask
      - maven
      - packer
      - awscli
      - hg
      - lnav
      - htop
      - nmap
      - httpie
      - jq
      - hugo
    homebrew_taps:
      - caskroom/cask
      - caskroom/versions
      - homebrew/binary
    homebrew_cask_apps:
      - sublime-text
      - facter
      - hiera
      - puppet
      - atom
    rvm1_install_flags: '--user-install'

  roles:
    - { role: geerlingguy.homebrew }
    #- { role: rvm_io.rvm1-ruby }

  tasks:

  - name: Ensure SSH directory exists
    file: path={{ home }}/.ssh state=directory

  - name: Ensure workspace directory exists
    file: path={{ workspace }} state=directory

  - name: Set SSH configuration
    file: src={{ workspace }}/dotfiles/ssh/{{ item }} dest={{ home }}/.ssh/{{ item }} state=link
    with_items:
      - config
      - konoha_id_rsa
      - konoha_id_rsa.pub

  - name: Set Sendman configuration for GD hosts
    template: src={{ workspace }}/dotfiles/studio/sendman/{{ item }}.json dest={{ home }}/.ssh/{{ item }}.json
    with_items:
      - deidara
      - kakuzu
      - kisame

  - name: Set PyPI configuration
    template: src={{ workspace }}/dotfiles/python/.pypirc dest={{ home }}/.pypirc

  - name: Set npm configuration
    file: src={{ workspace }}/dotfiles/node/.npmrc dest={{ home }}/.npmrc state=link

  - name: Set Repoman configuration for project repositories
    file: src={{ workspace }}/dotfiles/studio/.repoman.json dest={{ home }}/.repoman.json state=link

  - name: Ensure .profile file exists
    file: path={{ home }}/.profile state=touch mode=0644

  - name: Set .profile
    lineinfile: dest={{ home }}/.profile line="{{ item }}" state=present backup=yes
    with_items:
      - export PATH=~/dev/go/bin:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/local/rvm/bin:$PATH
      - source ~/.virtualenv/local/bin/activate
      - source ~/.nvm/nvm.sh && nvm use default
      - export JAVA_HOME=`/usr/libexec/java_home -v 1.7`
      - export JENKINS_URL=http://pakkun.local:8080
      - export M2_HOME=/usr/local/homebrew/Cellar/maven/3.2.5/libexec
      - alias resize-images='find . -iname \"*.*\" -exec mogrify -resize 1024x1024 {} \;'
      - alias gpp='git pull --rebase && git push'
